# Generated by Django 5.2.8 on 2025-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_userprofile_assets_count_creatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
