# Generated by Django 5.2.8 on 2025-11-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_creatorprofile_username_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorprofile',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
