# Generated by Django 5.2.8 on 2025-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_username_creatorprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('eth', 'Ethereum (ETH)'), ('btc', 'Bitcoin (BTC)'), ('usdt', 'Tether (USDT)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
