# Generated by Django 5.2.8 on 2025-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creator_wallet_address',
            field=models.CharField(blank=True, help_text="Creator's wallet address for payment", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
