# Generated by Django 5.2.8 on 2025-11-22 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_nft_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(blank=True, default='No Owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_nfts', to=settings.AUTH_USER_MODEL),
        ),
    ]
