# Generated by Django 5.2.8 on 2025-11-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_nft_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nfts/'),
        ),
    ]
