# Generated by Django 5.2.8 on 2025-12-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='listing_date',
            field=models.DateTimeField(blank=True, help_text='Waktu listing otomatis jika status pre-listing', null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pre_listing', 'Pre-Listing'), ('listed', 'Listed'), ('sold', 'Sold')], default='draft', max_length=20),
        ),
    ]
