# Generated by Django 6.0 on 2025-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_nft_listing_date_alter_nft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total pembelian dalam ETH', max_digits=15),
        ),
    ]
